"""Materialize the R1.7 loss-weight sensitivity configs.

Each emitted YAML is a clone of ``configs/seq50_ultrasam.yaml`` with one loss
weight (or one bundle of weights) varied.

Axes:
  - lambda_CE      in {0.10, 0.25, 0.50, 1.00, 2.00}; others held at base.
  - lambda_temp    in {0, 1, 2.5, 5, 10, 20};        others held at base.
  - lambda_spatial in {0, 1, 2.5, 5, 10, 20} as a joint scale on the three
                   spatial auxiliaries (positive, negative, exclusion);
                   others held at base.

Center point (CE=0.5, temp=5, spatial=5) is the existing ``seq50_ultrasam``
run and is reused, not retrained. The spatial=0 endpoint is the existing
``dicecetemp_ultrasam`` run and is reused.

Usage:
    PYTHONPATH=. python data/build_r17_configs.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "configs" / "r17"

# Base loss-weight tuple (CE, temp, positive, negative, exclusion).
BASE = {"ce": 0.5, "temp": 5, "pos": 5, "neg": 5, "excl": 5}

# Class weights — re-use the inverse-freq scheme from the seq50_ultrasam anchor
# so the only varying quantity in this sweep is the loss-weight knob.
CE_CLASS_WEIGHTS = [1.0, 0.9417, 0.9339, 0.2813, 0.67, 0.2939, 3.5373, 0.7559, 0.586]

# Existing runs already covering specific sweep points (do not regenerate).
# Tag -> (existing_lightning_logs_dir, note).
REUSE = {
    "ce0.50":      ("seq50_ultrasam",      "center: identical to anchor"),
    "temp5":       ("seq50_ultrasam",      "center: identical to anchor"),
    "spatial5":    ("seq50_ultrasam",      "center: identical to anchor"),
    "spatial0":    ("dicecetemp_ultrasam", "ce=0.5, temp=5, pos=neg=excl=0"),
}

# New configs to generate (others held at BASE).
SWEEP = []
for ce in (0.10, 0.25, 1.00, 2.00):  # 0.50 is the center, reused.
    SWEEP.append(("ce", f"ce{ce:.2f}", {"ce": ce}))
for t in (0, 1, 2.5, 10, 20):  # 5 is the center, reused.
    SWEEP.append(("temp", f"temp{t}", {"temp": t}))
for a in (1, 2.5, 10, 20):  # spatial=0 reused (dicecetemp); 5 reused (anchor).
    SWEEP.append(("spatial", f"spatial{a}", {"pos": a, "neg": a, "excl": a}))


def _format_yaml(weights: dict) -> str:
    """Emit a YAML config string. Match the hand-written formatting of
    seq50_ultrasam.yaml so a `diff` against the anchor is minimal and readable.
    """
    return f"""# R1.7 loss-weight sweep — auto-generated by data/build_r17_configs.py.
# All other hyperparameters are identical to the unweighted headline (r15_noweights)
# so the only varying quantity is the loss-weight knob noted above. 5 seeds.
# Unweighted CE: ce_class_weights omitted (R1.7 unweighted retrain, 2026-05-26).
trainer:
  max_epochs: 20
  gpus: [0,1,2,3]
  ckpt_path: null

model:
  encoder_name: 'mit_b0'
  segmentation_model_name: 'Segformer'
  temporal_model: 'ConvLSTM'
  conv_type: "depthwise"
  num_classes: 8
  freeze_encoder: false
  num_layers: 1
  kernel_size: [3, 3]
  dilation: 1
  encoder_depth: 5
  temporal_depth: 4
  model_kwargs:
    decoder_segmentation_channels: 256
  learning_rate: 1.0e-3
  image_size: [416, 416]
  ce_weight: {weights['ce']}
  temporal_loss_weight: {weights['temp']}
  exclusion_weight: {weights['excl']}
  positive_weight: {weights['pos']}
  negative_weight: {weights['neg']}

data:
  train:
    data_path: './data/SUIT/images/sonosite_train'
    annotations_path: './data/SUIT/coco_annotations/sonosite_train_ultrasam.json'
    sequence_length: 50
    batch_size: 2
    truncated_bptt_steps: 10
  val:
    data_path: './data/SUIT/images/sonosite_val'
    annotations_path: './data/SUIT/coco_annotations/sonosite_val_ultrasam.json'
    sequence_length: 50
    batch_size: 2
    truncated_bptt_steps: 10
  num_workers: 12

logging:
  monitor: 'val_loss'
  mode: 'min'
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for axis, tag, overrides in SWEEP:
        weights = {**BASE, **overrides}
        path = OUT_DIR / f"r17_{tag}_ultrasam.yaml"
        path.write_text(_format_yaml(weights))
        written.append(path.relative_to(ROOT))
    for tag, (run, note) in REUSE.items():
        print(f"  REUSE  {tag:12s}  <- lightning_logs/{run}  ({note})")
    print(f"Wrote {len(written)} configs to {OUT_DIR.relative_to(ROOT)}/")
    for p in written:
        print(f"  {p}")


if __name__ == "__main__":
    main()
